import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The docs sidebar is generated automatically from the folder structure in
 * `docs/`. Order and labels for each section come from its `_category_.json`,
 * and each page's `sidebar_position` orders pages within a section.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
